// semcomp/RenderEngine.h — bulk-ported routines (auto-generated).
#pragma once

#include <cstdint>

namespace smb::semcomp {

class GameState;

class RenderEngine {
public:
    explicit RenderEngine(GameState& state) : state_(state) {}

    void sprite_shuffler();  // $81C6 SpriteShuffler (entry 0)
    void at_8200();  // $8200 at_8200 (entry 1)
    void set_misc_offset();  // $81F9 SetMiscOffset (entry 2)
    void oper_mode_execution_tree();  // $8212 OperModeExecutionTree (entry 0)
    void at_8222();  // $8222 at_8222 (entry 1)
    void draw_mushroom_icon();  // $8325 DrawMushroomIcon (entry 0)
    void at_8330();  // $8330 at_8330 (entry 1)
    void player_victory_walk();  // $83BD PlayerVictoryWalk (entry 0)
    void eval_for_music();  // $8434 EvalForMusic (entry 1)
    void at_8436();  // $8436 at_8436 (entry 2)
    void at_842c();  // $842C at_842c (entry 3)
    void at_8404();  // $8404 at_8404 (entry 4)
    void player_end_world();  // $8461 PlayerEndWorld (entry 0)
    void end_exit_one();  // $8486 EndExitOne (entry 1)
    void screen_routines();  // $8567 ScreenRoutines (entry 0)
    void at_85ad();  // $85AD at_85ad (entry 1)
    void do_nothing1();  // $92AA DoNothing1 (entry 0)
    void do_nothing2();  // $92AF DoNothing2 (entry 1)
    void scroll_handler();  // $AF93 ScrollHandler (entry 0)
    void at_afb1();  // $AFB1 at_afb1 (entry 1)
    void run_game_timer();  // $B74F RunGameTimer (entry 0)
    void ex_g_timer();  // $B7A3 ExGTimer (entry 1)
    void move_d_enemy_vertically();  // $BF63 MoveD_EnemyVertically (entry 0)
    void move_falling_platform();  // $BF6B MoveFallingPlatform (entry 1)
    void enemy_gfx_handler();  // $E87D EnemyGfxHandler (entry 0)
    void at_e9a0();  // $E9A0 at_e9a0 (entry 1)
    void at_e939();  // $E939 at_e939 (entry 2)
    void at_e9b2();  // $E9B2 at_e9b2 (entry 3)
    void at_e96d();  // $E96D at_e96d (entry 4)
    void check_for_goomba();  // $E900 CheckForGoomba (entry 5)
    void at_e998();  // $E998 at_e998 (entry 6)
    void at_eb20();  // $EB20 at_eb20 (entry 7)
    void at_e96f();  // $E96F at_e96f (entry 8)
    void at_e987();  // $E987 at_e987 (entry 9)
    void at_e9b6();  // $E9B6 at_e9b6 (entry 10)
    void at_e9d6();  // $E9D6 at_e9d6 (entry 11)
    void at_e908();  // $E908 at_e908 (entry 12)
    void at_eb86();  // $EB86 at_eb86 (entry 13)
    void at_e921();  // $E921 at_e921 (entry 14)
    void at_eba4();  // $EBA4 at_eba4 (entry 15)
    void at_eb84();  // $EB84 at_eb84 (entry 16)
    void at_eba6();  // $EBA6 at_eba6 (entry 17)
    void at_eaad();  // $EAAD at_eaad (entry 18)
    void at_eae7();  // $EAE7 at_eae7 (entry 19)
    void at_e9eb();  // $E9EB at_e9eb (entry 20)
    void at_ea3d();  // $EA3D at_ea3d (entry 21)
    void at_eaba();  // $EABA at_eaba (entry 22)
    void at_e9d0();  // $E9D0 at_e9d0 (entry 23)
    void at_e9e0();  // $E9E0 at_e9e0 (entry 24)
    void at_e919();  // $E919 at_e919 (entry 25)
    void at_ea20();  // $EA20 at_ea20 (entry 26)
    void check_bowser_rear();  // $E94C CheckBowserRear (entry 27)
    void at_e960();  // $E960 at_e960 (entry 28)
    void at_e9a4();  // $E9A4 at_e9a4 (entry 29)
    void at_ead0();  // $EAD0 at_ead0 (entry 30)
    void at_ea85();  // $EA85 at_ea85 (entry 31)
    void at_e928();  // $E928 at_e928 (entry 32)
    void at_eb80();  // $EB80 at_eb80 (entry 33)
    void at_ea32();  // $EA32 at_ea32 (entry 34)
    void at_e962();  // $E962 at_e962 (entry 35)
    void skip_to_off_scr_chk();  // $EA61 SkipToOffScrChk (entry 36)
    void at_e953();  // $E953 at_e953 (entry 37)
    void at_e9b0();  // $E9B0 at_e9b0 (entry 38)
    void at_e9d4();  // $E9D4 at_e9d4 (entry 39)
    void at_eb79();  // $EB79 at_eb79 (entry 40)
    void at_e902();  // $E902 at_e902 (entry 41)
    void draw_bowser();  // $E949 DrawBowser (entry 42)
    void at_eae1();  // $EAE1 at_eae1 (entry 43)
    void move_e_spr_row_offscreen();  // $EBB7 MoveESprRowOffscreen (entry 0)
    void at_ebb8();  // $EBB8 at_ebb8 (entry 1)
    void at_ebbc();  // $EBBC at_ebbc (entry 2)
    void move_e_spr_col_offscreen();  // $EBC1 MoveESprColOffscreen (entry 0)
    void at_ebc6();  // $EBC6 at_ebc6 (entry 1)
    void at_ebc2();  // $EBC2 at_ebc2 (entry 2)
    void draw_block();  // $EBD1 DrawBlock (entry 0)
    void at_ec20();  // $EC20 at_ec20 (entry 1)
    void set_b_flip();  // $EC21 SetBFlip (entry 2)
    void d_blk_loop();  // $EBE7 DBlkLoop (entry 3)
    void at_ebec();  // $EBEC at_ebec (entry 4)
    void at_ec23();  // $EC23 at_ec23 (entry 5)
    void at_ebea();  // $EBEA at_ebea (entry 6)
    void blk_offscr();  // $EC35 BlkOffscr (entry 7)
    void at_ec00();  // $EC00 at_ec00 (entry 8)
    void draw_brick_chunks();  // $EC53 DrawBrickChunks (entry 0)
    void at_ec91();  // $EC91 at_ec91 (entry 1)
    void at_ec85();  // $EC85 at_ec85 (entry 2)
    void at_eca5();  // $ECA5 at_eca5 (entry 3)
    void d_chunks();  // $EC65 DChunks (entry 4)
    void draw_fireball();  // $ECDE DrawFireball (entry 0)
    void at_ecf0();  // $ECF0 at_ecf0 (entry 1)
    void at_ecf1();  // $ECF1 at_ecf1 (entry 2)
    void draw_explosion_fireball();  // $ED09 DrawExplosion_Fireball (entry 0)
    void at_ed20();  // $ED20 at_ed20 (entry 1)
    void at_ed18();  // $ED18 at_ed18 (entry 2)
    void at_ed2e();  // $ED2E at_ed2e (entry 3)
    void draw_small_platform();  // $ED66 DrawSmallPlatform (entry 0)
    void s_ofs2();  // $EDD1 SOfs2 (entry 1)
    void at_ed6f();  // $ED6F at_ed6f (entry 2)
    void at_edc5();  // $EDC5 at_edc5 (entry 3)
    void at_ed86();  // $ED86 at_ed86 (entry 4)
    void at_eda6();  // $EDA6 at_eda6 (entry 5)
    void at_edb9();  // $EDB9 at_edb9 (entry 6)
    void at_ed76();  // $ED76 at_ed76 (entry 7)
    void draw_bubble();  // $EDE1 DrawBubble (entry 0)
    void ex_d_bub();  // $EE06 ExDBub (entry 1)
    void at_ee03();  // $EE03 at_ee03 (entry 2)
    void at_eded();  // $EDED at_eded (entry 3)
    void at_ede3();  // $EDE3 at_ede3 (entry 4)
    void at_ede4();  // $EDE4 at_ede4 (entry 5)
    void at_ede6();  // $EDE6 at_ede6 (entry 6)
    void at_ee01();  // $EE01 at_ee01 (entry 7)
    void render_player_sub();  // $EFBE RenderPlayerSub (entry 0)
    void at_efd1();  // $EFD1 at_efd1 (entry 1)
    void at_efdf();  // $EFDF at_efdf (entry 2)
    void process_player_action();  // $EFEC ProcessPlayerAction (entry 0)
    void at_f008();  // $F008 at_f008 (entry 1)
    void at_f041();  // $F041 at_f041 (entry 2)
    void at_f004();  // $F004 at_f004 (entry 3)
    void at_f006();  // $F006 at_f006 (entry 4)
    void at_f012();  // $F012 at_f012 (entry 5)
    void at_f010();  // $F010 at_f010 (entry 6)
    void at_f058();  // $F058 at_f058 (entry 7)
    void at_f02d();  // $F02D at_f02d (entry 8)
    void at_f001();  // $F001 at_f001 (entry 9)
    void at_f021();  // $F021 at_f021 (entry 10)
    void action_walk_run();  // $F03C ActionWalkRun (entry 11)
    void at_f01f();  // $F01F at_f01f (entry 12)
    void at_eff0();  // $EFF0 at_eff0 (entry 13)
    void at_f046();  // $F046 at_f046 (entry 14)
    void at_f014();  // $F014 at_f014 (entry 15)
    void at_f00d();  // $F00D at_f00d (entry 16)
    void at_f030();  // $F030 at_f030 (entry 17)
    void at_f033();  // $F033 at_f033 (entry 18)
    void at_f025();  // $F025 at_f025 (entry 19)
    void action_falling();  // $F034 ActionFalling (entry 20)
    void at_f02b();  // $F02B at_f02b (entry 21)
    void proc_on_ground_acts();  // $F00B ProcOnGroundActs (entry 22)
    void at_f01d();  // $F01D at_f01d (entry 23)
    void at_f027();  // $F027 at_f027 (entry 24)
    void at_f05f();  // $F05F at_f05f (entry 25)
    void at_f060();  // $F060 at_f060 (entry 26)
    void at_f016();  // $F016 at_f016 (entry 27)
    void at_effd();  // $EFFD at_effd (entry 28)
    void at_f048();  // $F048 at_f048 (entry 29)
    void action_swimming();  // $F050 ActionSwimming (entry 30)
    void at_f03e();  // $F03E at_f03e (entry 31)
    void at_f065();  // $F065 at_f065 (entry 32)
    void at_f018();  // $F018 at_f018 (entry 33)
    void at_f05d();  // $F05D at_f05d (entry 34)
    void at_f052();  // $F052 at_f052 (entry 35)
    void at_f01a();  // $F01A at_f01a (entry 36)
    void at_f06a();  // $F06A at_f06a (entry 37)
    void at_f023();  // $F023 at_f023 (entry 38)
    void at_f039();  // $F039 at_f039 (entry 39)
    void three_frame_extent();  // $F06D ThreeFrameExtent (entry 0)
    void at_f090();  // $F090 at_f090 (entry 1)
    void at_f086();  // $F086 at_f086 (entry 2)
    void at_f07d();  // $F07D at_f07d (entry 3)
    void at_f074();  // $F074 at_f074 (entry 4)
    void at_f075();  // $F075 at_f075 (entry 5)
    void at_f080();  // $F080 at_f080 (entry 6)
    void at_f088();  // $F088 at_f088 (entry 7)
    void get_gfx_offset_adder();  // $F091 GetGfxOffsetAdder (entry 0)
    void at_f098();  // $F098 at_f098 (entry 1)
    void handle_change_size();  // $F0B0 HandleChangeSize (entry 0)
    void at_f0e1();  // $F0E1 at_f0e1 (entry 1)
    void c_sz_next();  // $F0C3 CSzNext (entry 2)
    void at_f0b9();  // $F0B9 at_f0b9 (entry 3)
    void at_f0ba();  // $F0BA at_f0ba (entry 4)
    void at_f0c9();  // $F0C9 at_f0c9 (entry 5)
    void gor_s_log();  // $F0C6 GorSLog (entry 6)
    void at_f0e3();  // $F0E3 at_f0e3 (entry 7)
    void at_f0de();  // $F0DE at_f0de (entry 8)
    void at_f0cb();  // $F0CB at_f0cb (entry 9)
    void at_f0d8();  // $F0D8 at_f0d8 (entry 10)
    void at_f0d9();  // $F0D9 at_f0d9 (entry 11)
    void at_f0d1();  // $F0D1 at_f0d1 (entry 12)
    void at_f0c0();  // $F0C0 at_f0c0 (entry 13)
    void at_f0e8();  // $F0E8 at_f0e8 (entry 14)
    void at_f0be();  // $F0BE at_f0be (entry 15)
    void chk_for_player_attrib();  // $F0E9 ChkForPlayerAttrib (entry 0)
    void at_f0f0();  // $F0F0 at_f0f0 (entry 1)
    void at_f110();  // $F110 at_f110 (entry 2)
    void at_f0f9();  // $F0F9 at_f0f9 (entry 3)
    void at_f0fd();  // $F0FD at_f0fd (entry 4)
    void at_f0ee();  // $F0EE at_f0ee (entry 5)
    void at_f0fb();  // $F0FB at_f0fb (entry 6)
    void at_f0ff();  // $F0FF at_f0ff (entry 7)
    void at_f0f2();  // $F0F2 at_f0f2 (entry 8)
    void at_f0f5();  // $F0F5 at_f0f5 (entry 9)
    void at_f11f();  // $F11F at_f11f (entry 10)
    void relative_misc_position();  // $F148 RelativeMiscPosition (entry 0)
    void at_f14d();  // $F14D at_f14d (entry 1)
    void get_player_offscreen_bits();  // $F180 GetPlayerOffscreenBits (entry 0)
    void at_f184();  // $F184 at_f184 (entry 1)
    void get_misc_offscreen_bits();  // $F19B GetMiscOffscreenBits (entry 0)
    void at_f19d();  // $F19D at_f19d (entry 1)
    void get_proper_obj_offset();  // $F1A8 GetProperObjOffset (entry 0)
    void get_obj_relative_position();  // $F171 GetObjRelativePosition (owned: OAM identity)
    void at_f1a9();  // $F1A9 at_f1a9 (entry 1)
    void get_enemy_offscreen_bits();  // $F1AF GetEnemyOffscreenBits (entry 0)
    void at_f1b1();  // $F1B1 at_f1b1 (entry 1)
    void get_block_offscreen_bits();  // $F1B6 GetBlockOffscreenBits (entry 0)
    void at_f1d1();  // $F1D1 at_f1d1 (entry 1)
    void at_f1bd();  // $F1BD at_f1bd (entry 2)
    void at_f1bc();  // $F1BC at_f1bc (entry 3)
    void at_f1c1();  // $F1C1 at_f1c1 (entry 4)
    void at_f1ce();  // $F1CE at_f1ce (entry 5)
    void get_y_offscreen_bits();  // $F239 GetYOffscreenBits (entry 0)
    void y_ofs_loop();  // $F23D YOfsLoop (entry 1)
    void draw_sprite_object();  // $F282 DrawSpriteObject (entry 0)
    void at_f2bd();  // $F2BD at_f2bd (entry 1)
    void at_f285();  // $F285 at_f285 (entry 2)
    void at_f286();  // $F286 at_f286 (entry 3)
    void at_f2a5();  // $F2A5 at_f2a5 (entry 4)
    void at_f284();  // $F284 at_f284 (entry 5)
    void at_f2c8();  // $F2C8 at_f2c8 (entry 6)
    void at_f288();  // $F288 at_f288 (entry 7)

private:
    void sprite_shuffler_body(int _entry);  // shared body for $81C6_b0 /* SpriteShuffler */
    void oper_mode_execution_tree_body(int _entry);  // shared body for $8212_b0 /* OperModeExecutionTree */
    void draw_mushroom_icon_body(int _entry);  // shared body for $8325_b0 /* DrawMushroomIcon */
    void player_victory_walk_body(int _entry);  // shared body for $83BD_b0 /* PlayerVictoryWalk */
    void player_end_world_body(int _entry);  // shared body for $8461_b0 /* PlayerEndWorld */
    void screen_routines_body(int _entry);  // shared body for $8567_b0 /* ScreenRoutines */
    void do_nothing1_body(int _entry);  // shared body for $92AA_b0 /* DoNothing1 */
    void scroll_handler_body(int _entry);  // shared body for $AF93_b0 /* ScrollHandler */
    void run_game_timer_body(int _entry);  // shared body for $B74F_b0 /* RunGameTimer */
    void move_d_enemy_vertically_body(int _entry);  // shared body for $BF63_b0 /* MoveD_EnemyVertically */
    void enemy_gfx_handler_body(int _entry);  // shared body for $E87D /* EnemyGfxHandler */
    void move_e_spr_row_offscreen_body(int _entry);  // shared body for $EBB7 /* MoveESprRowOffscreen */
    void move_e_spr_col_offscreen_body(int _entry);  // shared body for $EBC1 /* MoveESprColOffscreen */
    void draw_block_body(int _entry);  // shared body for $EBD1 /* DrawBlock */
    void draw_brick_chunks_body(int _entry);  // shared body for $EC53 /* DrawBrickChunks */
    void draw_fireball_body(int _entry);  // shared body for $ECDE /* DrawFireball */
    void draw_explosion_fireball_body(int _entry);  // shared body for $ED09 /* DrawExplosion_Fireball */
    void draw_small_platform_body(int _entry);  // shared body for $ED66 /* DrawSmallPlatform */
    void draw_bubble_body(int _entry);  // shared body for $EDE1 /* DrawBubble */
    void render_player_sub_body(int _entry);  // shared body for $EFBE /* RenderPlayerSub */
    void process_player_action_body(int _entry);  // shared body for $EFEC /* ProcessPlayerAction */
    void three_frame_extent_body(int _entry);  // shared body for $F06D /* ThreeFrameExtent */
    void get_gfx_offset_adder_body(int _entry);  // shared body for $F091 /* GetGfxOffsetAdder */
    void handle_change_size_body(int _entry);  // shared body for $F0B0 /* HandleChangeSize */
    void chk_for_player_attrib_body(int _entry);  // shared body for $F0E9 /* ChkForPlayerAttrib */
    void relative_misc_position_body(int _entry);  // shared body for $F148 /* RelativeMiscPosition */
    void get_player_offscreen_bits_body(int _entry);  // shared body for $F180 /* GetPlayerOffscreenBits */
    void get_misc_offscreen_bits_body(int _entry);  // shared body for $F19B /* GetMiscOffscreenBits */
    void get_proper_obj_offset_body(int _entry);  // shared body for $F1A8 /* GetProperObjOffset */
    void get_enemy_offscreen_bits_body(int _entry);  // shared body for $F1AF /* GetEnemyOffscreenBits */
    void get_block_offscreen_bits_body(int _entry);  // shared body for $F1B6 /* GetBlockOffscreenBits */
    void get_y_offscreen_bits_body(int _entry);  // shared body for $F239 /* GetYOffscreenBits */
    void draw_sprite_object_body(int _entry);  // shared body for $F282 /* DrawSpriteObject */
    GameState& state_;
};

}  // namespace smb::semcomp
