"""Generate cycle-call adapters from SMB's pinned symbol map (no CPU code).

Run after changing the trusted game modules. --check verifies checked-in files.
The original bank-zero alias is retained for existing power-up policy calls.
"""
import argparse
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
symbols = {}
for line in (root/'symbols.sym').read_text().splitlines():
    match = re.fullmatch(r'([0-9a-fA-F]+)\s+(\w+)\s+(\w+)', line)
    if match:
        symbols[match[2]] = (int(match[1], 16), match[3])
excluded = {'extras.c', 'watchdog.c', 'verify_mode.c', 'nes_snapshot.c',
            'cycle_calls.c', 'cycle_bridge.c', 'cycle_extras.c'}
source = '\n'.join(p.read_text() for p in sorted((root/'src').glob('*.c')) if p.name not in excluded)
used = set(re.findall(r'\b\w+\b', source))
functions = {'PowerUpObjHandler__b0': symbols['PowerUpObjHandler'][0]}
lines = ['/* Generated by tools/generate_cycle_symbols.py from pinned symbols.sym. */', '#pragma once']
for name, (address, kind) in symbols.items():
    if name not in used:
        continue
    if kind == 'func':
        fn = f'func_{address:04X}' + ('_b0' if address < 0xc000 else '')
        lines.append(f'#define {name} {fn}')
        functions[fn] = address
    else:
        lines.append(f'#define {name} 0x{address:04X}u')
for address, suffix in re.findall(r'\bfunc_([0-9A-F]{4})(_b0)?\b', source):
    functions['func_'+address+suffix] = int(address, 16)
lines.extend(f'void {name}(void);' for name in sorted(functions))
outputs = {
    root/'src/smb_cycle_symbols.h': '\n'.join(lines)+'\n',
    root/'src/cycle_calls.c': '#include "cycle_bridge.h"\n' + ''.join(
        f'void {name}(void) {{ smb1_cycle_call(0x{address:04x}); }}\n' for name, address in sorted(functions.items())),
}
for path, text in outputs.items():
    if args.check:
        if path.read_text() != text:
            raise SystemExit(f'{path.relative_to(root)} needs regeneration')
    else:
        path.write_text(text)
print('Cycle symbol adapters verified' if args.check else 'Cycle symbol adapters regenerated')
