"""Extract the co-op adapter's symbols from the pinned SMB disassembly.

RAM names come from the assembly; code labels come from the checked-in symbol
map generated by ca65/ld65. No generated recompiler output is edited.
"""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
asm = (root / "smb-disassembly/src/smb.asm").read_text()
names = {m[1]: int(m[2], 16) for m in re.finditer(
    r"^(\w+)\s*=\s*\$([0-9a-fA-F]+)\b", asm, re.M)}
for line in (root / "symbols.sym").read_text().splitlines():
    m = re.fullmatch(r"([0-9A-Fa-f]+)\s+(\w+)\s+func", line)
    if m:
        names[m[2]] = int(m[1], 16)
out = root / "src/coop/smb_symbols.h"
out.parent.mkdir(parents=True, exist_ok=True)
adapter = (root / "src/game_coop.c").read_text()
used = set(re.findall(r"\bS_(\w+)", adapter))
used.update(re.findall(r"\bFIELD\((\w+),", adapter))
used.discard("name")  # FIELD macro's formal argument
missing = used - names.keys()
if missing:
    raise SystemExit(f"Unknown disassembly symbols: {sorted(missing)}")
out.write_text("/* Generated by tools/generate_coop_symbols.py. */\n#pragma once\n" +
               "".join(f"#define S_{k} 0x{names[k]:04x}u\n" for k in sorted(used)))
