/* Generated by tools/generate_cycle_symbols.py from pinned symbols.sym. */
#pragma once
#define Start func_8000_b0
#define OperModeExecutionTree func_8212_b0
#define TitleScreenMode func_8231_b0
#define VictoryMode func_838B_b0
#define SetVRAMAddr_B func_864C_b0
#define DrawTitleScreen func_86FF_b0
#define DestroyBlockMetatile func_8A6B_b0
#define WriteBlockMetatile func_8A6D_b0
#define UpdateScreen func_8EDD_b0
#define InitializeArea func_8FE4_b0
#define Entrance_GameTimerSetup func_9131_b0
#define PlayerLoseLife func_91CD_b0
#define GameOverMode func_9218_b0
#define AreaParserTaskHandler func_92B0_b0
#define AreaParserCore func_93FC_b0
#define Jumpspring func_9AD3_b0
#define E_UndergroundArea3 func_A133_b0
#define GameMode func_AEDC_b0
#define GameCoreRoutine func_AEEA_b0
#define GameEngine func_AEFE_b0
#define SaveAB func_AF67_b0
#define UpdScrollVar func_AF6F_b0
#define ScrollHandler func_AF93_b0
#define ChkPOffscr func_B000_b0
#define KeepOnscr func_B013_b0
#define GameRoutines func_B04A_b0
#define PlayerEntrance func_B069_b0
#define PlayerRdy func_B0D3_b0
#define PlayerCtrlRoutine func_B0E9_b0
#define SaveJoyp func_B104_b0
#define Vine_AutoClimb func_B1C7_b0
#define VerticalPipeEntry func_B1E5_b0
#define SideExitPipeEntry func_B206_b0
#define PlayerChangeSize func_B233_b0
#define PlayerInjuryBlink func_B245_b0
#define PlayerDeath func_B269_b0
#define PlayerFireFlower func_B27D_b0
#define FlagpoleSlide func_B2A4_b0
#define PlayerEndLevel func_B2CA_b0
#define ProcMove func_B33B_b0
#define GndMove func_B363_b0
#define JumpSwimSub func_B376_b0
#define DumpFall func_B38D_b0
#define ProcSwim func_B393_b0
#define LRAir func_B3AC_b0
#define JSMove func_B3B3_b0
#define PlayerYSpdData func_B432_b0
#define MaxRightXSpdData func_B443_b0
#define PlayerPhysicsSub func_B450_b0
#define CheckForJumping func_B479_b0
#define InitJS func_B4A0_b0
#define ImposeFriction func_B5CC_b0
#define ProcessWhirlpools func_B7B8_b0
#define JumpspringHandler func_B8BA_b0
#define Setup_Vine func_B91E_b0
#define FindEmptyMiscSlot func_BB84_b0
#define ProcJumpCoin func_BBA7_b0
#define JCoinRun func_BBC9_b0
#define CoinTallyOffsets func_BBF8_b0
#define GiveOneCoin func_BBFE_b0
#define AddToScore func_BC27_b0
#define GetSBNybbles func_BC30_b0
#define SetupPowerUp func_BC49_b0
#define PowerUpObjHandler func_BC85_b0
#define BlockYPosAdderData func_BCEB_b0
#define PlayerHeadCollision func_BCED_b0
#define InitBlock_XY_Pos func_BD84_b0
#define BumpBlock func_BD9B_b0
#define MushFlowerBlock func_BDD2_b0
#define StarBlock func_BDD5_b0
#define ExtraLifeMushBlock func_BDD8_b0
#define BrickQBlockMetatiles func_BDE8_b0
#define BlockBumpedChk func_BDF6_b0
#define BrickShatter func_BE02_b0
#define SpawnBrickChunks func_BE41_b0
#define BlockObjectsCore func_BE70_b0
#define BouncingBlockHandler func_BEB3_b0
#define BlockObjMT_Updater func_BED4_b0
#define MoveEnemyHorizontally func_BF02_b0
#define MovePlayerHorizontally func_BF09_b0
#define MoveObjectHorizontally func_BF0F_b0
#define ExXMove func_BF4C_b0
#define MovePlayerVertically func_BF4D_b0
#define MaxSpdBlockData func_BF9F_b0
#define ImposeGravityBlock func_BFA4_b0
#define ImposeGravitySprObj func_BFAD_b0
#define ImposeGravity func_BFD7_b0
#define ExecGameLoopback func_C08C
#define CheckRightBounds func_C164
#define HandleGroupEnemies func_C71B
#define EraseEnemyObject func_C998
#define XMoveCntr_Platform func_CB47
#define MoveWithXMCntrs func_CB66
#define FirebarCollision func_CE08
#define XMovingPlatform func_D607
#define PositionPlayerOnHPlat func_D614
#define RightPlatform func_D63D
#define BowserIdentities func_D736
#define HandleEnemyFBallCol func_D73E
#define HurtBowser func_D75C
#define ShellOrBlockDefeat func_D795
#define HandlePowerUpCollision func_D800
#define KickedShellXSpdData func_D84F
#define PlayerEnemyCollision func_D853
#define KickedShellPtsData func_D892
#define HandlePECollisions func_D895
#define ChkForPlayerInjury func_D8F9
#define InjurePlayer func_D92C
#define ForceInjury func_D931
#define SetKRout func_D946
#define KillPlayer func_D958
#define EnemyStomped func_D969
#define SBnce func_D9F1
#define EnemyFacePlayer func_DA05
#define SetupFloateyNumber func_DA11
#define LargePlatformCollision func_DB45
#define SmallPlatformCollision func_DB7B
#define SetCollisionFlag func_DBEB
#define CheckPlayerVertical func_DC41
#define PlayerBGUpperExtent func_DC62
#define PlayerBGCollision func_DC64
#define SetFallS func_DC82
#define ChkOnScr func_DC86
#define ChkCollSize func_DC98
#define HeadChk func_DCBA
#define NYSpd func_DCF2
#define DoFootCheck func_DCF6
#define ChkFootMTile func_DD1D
#define LandPlyr func_DD44
#define DoPlayerSideCheck func_DD5E
#define SideCheckLoop func_DD66
#define BHalf func_DD85
#define CheckSideMTiles func_DD9C
#define ChkPBtm func_DDBB
#define HandleClimbing func_DE2E
#define ChkInvisibleMTiles func_DEBD
#define ImpedePlayerMove func_DF4B
#define SolidMTileUpperExt func_DF8B
#define CheckForSolidMTiles func_DF8F
#define CheckForClimbMTiles func_DF9A
#define CheckForCoinMTiles func_DFA1
#define GetMTileAttrib func_DFB0
#define EnemyBGCStateData func_DFB9
#define EnemyToBGCollisionDet func_DFC1
#define LandEnemyInitState func_E0CD
#define BoundingBoxCore func_E29C
#define PlayerCollisionCore func_E325
#define BlockBufferAdderData func_E3AD
#define BlockBuffer_X_Adder func_E3B0
#define BlockBuffer_Y_Adder func_E3CC
#define BlockBufferColli_Feet func_E3E8
#define BlockBufferColli_Head func_E3E9
#define BlockBufferColli_Side func_E3EC
#define BlockBufferCollision func_E3F0
#define DrawFloateyNumber_Coin func_E655
#define JumpingCoinTiles func_E682
#define JCoinGfxHandler func_E686
#define DrawPowerUp func_E6D2
#define DrawBlock func_EBD1
#define DrawBrickChunks func_EC53
#define PlayerGfxProcessing func_EF45
#define RenderPlayerSub func_EFBE
#define ActionSwimming func_F050
#define RelativeEnemyPosition func_F152
#define ObjectOffset 0x0008u
#define FrameCounter 0x0009u
#define A_B_Buttons 0x000Au
#define Left_Right_Buttons 0x000Cu
#define PreviousA_B_Buttons 0x000Du
#define GameEngineSubroutine 0x000Eu
#define Enemy_Flag 0x000Fu
#define Enemy_ID 0x0016u
#define Player_State 0x001Du
#define Enemy_State 0x001Eu
#define Fireball_State 0x0024u
#define Block_State 0x0026u
#define Misc_State 0x002Au
#define PlayerFacingDir 0x0033u
#define PowerUpType 0x0039u
#define FireballBouncingFlag 0x003Au
#define Player_MovingDir 0x0045u
#define Enemy_MovingDir 0x0046u
#define Player_X_Speed 0x0057u
#define SprObject_X_Speed 0x0057u
#define Enemy_X_Speed 0x0058u
#define XMoveSecondaryCounter 0x0058u
#define Fireball_X_Speed 0x005Eu
#define Player_PageLoc 0x006Du
#define Enemy_PageLoc 0x006Eu
#define Fireball_PageLoc 0x0074u
#define Block_PageLoc 0x0076u
#define Player_X_Position 0x0086u
#define SprObject_X_Position 0x0086u
#define Enemy_X_Position 0x0087u
#define Fireball_X_Position 0x008Du
#define Block_X_Position 0x008Fu
#define Player_Y_Speed 0x009Fu
#define Enemy_Y_Speed 0x00A0u
#define XMovePrimaryCounter 0x00A0u
#define Fireball_Y_Speed 0x00A6u
#define Player_Y_HighPos 0x00B5u
#define Enemy_Y_HighPos 0x00B6u
#define Fireball_Y_HighPos 0x00BCu
#define Block_Y_HighPos 0x00BEu
#define Player_Y_Position 0x00CEu
#define Enemy_Y_Position 0x00CFu
#define Fireball_Y_Position 0x00D5u
#define Block_Y_Position 0x00D7u
#define AreaData 0x00E7u
#define EnemyData 0x00E9u
#define NoiseSoundQueue 0x00FDu
#define Square2SoundQueue 0x00FEu
#define Square1SoundQueue 0x00FFu
#define DigitModifier 0x0134u
#define Sprite_Data 0x0200u
#define VRAM_Buffer1_Offset 0x0300u
#define VRAM_Buffer2_Offset 0x0340u
#define VRAM_Buffer2 0x0341u
#define BowserBodyControls 0x0363u
#define Platform_X_Scroll 0x03A1u
#define PlatformCollisionFlag 0x03A2u
#define Player_Rel_XPos 0x03ADu
#define Enemy_Rel_XPos 0x03AEu
#define Player_Rel_YPos 0x03B8u
#define Enemy_Rel_YPos 0x03B9u
#define Player_SprAttrib 0x03C4u
#define Enemy_SprAttrib 0x03C5u
#define Player_OffscreenBits 0x03D0u
#define Enemy_OffscreenBits 0x03D1u
#define EnemyOffscrBitsMasked 0x03D8u
#define Block_Orig_YPos 0x03E4u
#define Block_BBuf_Low 0x03E6u
#define Block_Metatile 0x03E8u
#define Block_PageLoc2 0x03EAu
#define Block_RepFlag 0x03ECu
#define SprDataOffset_Ctrl 0x03EEu
#define Block_Orig_XPos 0x03F1u
#define SprObject_X_MoveForce 0x0400u
#define Enemy_X_MoveForce 0x0401u
#define Player_YMF_Dummy 0x0416u
#define Enemy_YMF_Dummy 0x0417u
#define Player_Y_MoveForce 0x0433u
#define Enemy_Y_MoveForce 0x0434u
#define Block_Y_MoveForce 0x043Cu
#define MaximumLeftSpeed 0x0450u
#define MaximumRightSpeed 0x0456u
#define Cannon_Timer 0x047Du
#define Whirlpool_Flag 0x047Du
#define BowserHitPoints 0x0483u
#define StompChainCounter 0x0484u
#define Player_CollisionBits 0x0490u
#define Enemy_CollisionBits 0x0491u
#define Player_BoundBoxCtrl 0x0499u
#define SprObj_BoundBoxCtrl 0x0499u
#define Enemy_BoundBoxCtrl 0x049Au
#define Fireball_BoundBoxCtrl 0x04A0u
#define BoundingBox_UL_XPos 0x04ACu
#define BoundingBox_UL_YPos 0x04ADu
#define BoundingBox_DR_XPos 0x04AEu
#define BoundingBox_DR_YPos 0x04AFu
#define Block_Buffer_1 0x0500u
#define Block_Buffer_2 0x05D0u
#define BlockBufferColumnPos 0x06A0u
#define JumpCoinMiscOffset 0x06B7u
#define FireballCounter 0x06CEu
#define PlayerGfxOffset 0x06D5u
#define JumpspringForce 0x06DBu
#define Player_SprDataOffset 0x06E4u
#define Enemy_SprDataOffset 0x06E5u
#define SavedJoypadBits 0x06FCu
#define Player_X_Scroll 0x06FFu
#define Player_XSpeedAbsolute 0x0700u
#define SwimmingFlag 0x0704u
#define VerticalForce 0x0709u
#define JumpspringAnimCtrl 0x070Eu
#define FireballThrowingTimer 0x0711u
#define CrouchingFlag 0x0714u
#define DisableCollisionDet 0x0716u
#define ScreenLeft_PageLoc 0x071Au
#define ScreenLeft_X_Pos 0x071Cu
#define AreaParserTaskNum 0x071Fu
#define ScrollLock 0x0723u
#define CurrentPageLoc 0x0725u
#define CurrentColumnPos 0x0726u
#define ScrollThirtyTwo 0x073Du
#define TimerControl 0x0747u
#define AreaType 0x074Eu
#define AreaPointer 0x0750u
#define AltEntranceControl 0x0752u
#define CurrentPlayer 0x0753u
#define PlayerSize 0x0754u
#define Player_Pos_ForScroll 0x0755u
#define PlayerStatus 0x0756u
#define HalfwayPage 0x075Bu
#define CoinTally 0x075Eu
#define OperMode 0x0770u
#define OperMode_Task 0x0772u
#define VRAM_Buffer_AddrCtrl 0x0773u
#define ScrollAmount 0x0775u
#define GamePauseStatus 0x0776u
#define PlayerAnimTimer 0x0781u
#define BlockBounceTimer 0x0784u
#define SideCollisionTimer 0x0785u
#define JumpspringTimer 0x0786u
#define ClimbSideTimer 0x0789u
#define EnemyFrameTimer 0x078Au
#define StompTimer 0x0791u
#define EnemyIntervalTimer 0x0796u
#define InjuryTimer 0x079Eu
#define StarInvincibleTimer 0x079Fu
#define DisplayDigits 0x07D7u
#define GreenKoopa 0x0000u
#define BuzzyBeetle 0x0002u
#define RedKoopa 0x0003u
#define HammerBro 0x0005u
#define Goomba 0x0006u
#define Bloober 0x0007u
#define BulletBill_FrenzyVar 0x0008u
#define GreyCheepCheep 0x000Au
#define RedCheepCheep 0x000Bu
#define Podoboo 0x000Cu
#define PiranhaPlant 0x000Du
#define GreenParatroopaJump 0x000Eu
#define RedParatroopa 0x000Fu
#define GreenParatroopaFly 0x0010u
#define Lakitu 0x0011u
#define Spiny 0x0012u
#define FlyingCheepCheep 0x0014u
#define BowserFlame 0x0015u
#define Fireworks 0x0016u
#define Bowser 0x002Du
#define PowerUpObject 0x002Eu
#define BulletBill_CannonVar 0x0033u
void PowerUpObjHandler__b0(void);
void func_8000_b0(void);
void func_8212_b0(void);
void func_8231_b0(void);
void func_838B_b0(void);
void func_864C_b0(void);
void func_86FF_b0(void);
void func_8A6B_b0(void);
void func_8A6D_b0(void);
void func_8EDD_b0(void);
void func_8FE4_b0(void);
void func_9131_b0(void);
void func_91CD_b0(void);
void func_9218_b0(void);
void func_92B0_b0(void);
void func_93FC_b0(void);
void func_9AD3_b0(void);
void func_A133_b0(void);
void func_AEDC_b0(void);
void func_AEEA_b0(void);
void func_AEFE_b0(void);
void func_AF67_b0(void);
void func_AF6F_b0(void);
void func_AF93_b0(void);
void func_B000_b0(void);
void func_B013_b0(void);
void func_B04A_b0(void);
void func_B069_b0(void);
void func_B0D3_b0(void);
void func_B0E9_b0(void);
void func_B104_b0(void);
void func_B1C7_b0(void);
void func_B1E5_b0(void);
void func_B206_b0(void);
void func_B233_b0(void);
void func_B245_b0(void);
void func_B269_b0(void);
void func_B27D_b0(void);
void func_B2A4_b0(void);
void func_B2CA_b0(void);
void func_B33B_b0(void);
void func_B363_b0(void);
void func_B376_b0(void);
void func_B38D_b0(void);
void func_B393_b0(void);
void func_B3AC_b0(void);
void func_B3B3_b0(void);
void func_B432_b0(void);
void func_B443_b0(void);
void func_B450_b0(void);
void func_B479_b0(void);
void func_B4A0_b0(void);
void func_B5CC_b0(void);
void func_B7B8_b0(void);
void func_B8BA_b0(void);
void func_B91E_b0(void);
void func_BB84_b0(void);
void func_BBA7_b0(void);
void func_BBC9_b0(void);
void func_BBF8_b0(void);
void func_BBFE_b0(void);
void func_BC27_b0(void);
void func_BC30_b0(void);
void func_BC49_b0(void);
void func_BC85_b0(void);
void func_BCEB_b0(void);
void func_BCED_b0(void);
void func_BD84_b0(void);
void func_BD9B_b0(void);
void func_BDD2_b0(void);
void func_BDD5_b0(void);
void func_BDD8_b0(void);
void func_BDE8_b0(void);
void func_BDF6_b0(void);
void func_BE02_b0(void);
void func_BE41_b0(void);
void func_BE70_b0(void);
void func_BEB3_b0(void);
void func_BED4_b0(void);
void func_BF02_b0(void);
void func_BF09_b0(void);
void func_BF0F_b0(void);
void func_BF4C_b0(void);
void func_BF4D_b0(void);
void func_BF9F_b0(void);
void func_BFA4_b0(void);
void func_BFAD_b0(void);
void func_BFD7_b0(void);
void func_C08C(void);
void func_C164(void);
void func_C26C(void);
void func_C71B(void);
void func_C787(void);
void func_C905(void);
void func_C982(void);
void func_C998(void);
void func_CB47(void);
void func_CB66(void);
void func_CE08(void);
void func_D607(void);
void func_D614(void);
void func_D63D(void);
void func_D65B(void);
void func_D736(void);
void func_D73E(void);
void func_D75C(void);
void func_D795(void);
void func_D800(void);
void func_D84F(void);
void func_D853(void);
void func_D892(void);
void func_D895(void);
void func_D8F9(void);
void func_D92C(void);
void func_D931(void);
void func_D946(void);
void func_D958(void);
void func_D969(void);
void func_D9F1(void);
void func_DA05(void);
void func_DA11(void);
void func_DA33(void);
void func_DB45(void);
void func_DB7B(void);
void func_DBEB(void);
void func_DC41(void);
void func_DC62(void);
void func_DC64(void);
void func_DC82(void);
void func_DC86(void);
void func_DC98(void);
void func_DCBA(void);
void func_DCF2(void);
void func_DCF6(void);
void func_DD1D(void);
void func_DD44(void);
void func_DD5E(void);
void func_DD66(void);
void func_DD85(void);
void func_DD9C(void);
void func_DDBB(void);
void func_DE2E(void);
void func_DEBD(void);
void func_DF4B(void);
void func_DF8B(void);
void func_DF8F(void);
void func_DF9A(void);
void func_DFA1(void);
void func_DFB0(void);
void func_DFB9(void);
void func_DFC1(void);
void func_E0CD(void);
void func_E243(void);
void func_E29C(void);
void func_E325(void);
void func_E3AD(void);
void func_E3B0(void);
void func_E3CC(void);
void func_E3E8(void);
void func_E3E9(void);
void func_E3EC(void);
void func_E3F0(void);
void func_E54B(void);
void func_E5C8(void);
void func_E655(void);
void func_E682(void);
void func_E686(void);
void func_E6D2(void);
void func_E87D(void);
void func_EBD1(void);
void func_EC53(void);
void func_ED66(void);
void func_EF45(void);
void func_EFBE(void);
void func_F050(void);
void func_F152(void);
void func_F1AF(void);
